services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: codebook
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: always

  piston:
    image: ghcr.io/engineer-man/piston:latest
    container_name: piston_api
    platform: linux/amd64
    restart: always
    privileged: true
    ports:
      - "2000:2000"
    volumes:
      - piston_packages:/piston/packages

  piston_setup:
    image: alpine:latest
    depends_on:
      - piston
    entrypoint: 
      - /bin/sh
      - -c
      - |
        apk add --no-cache curl

        # installs language if not already installed
        install_language() {
          if ! curl -s http://piston:2000/api/v2/runtimes | grep -q "$1"; then
            curl -s -X POST http://piston:2000/api/v2/packages \
                 -H "Content-Type: application/json" \
                 -d "{\"language\": \"$1\", \"version\": \"$2\"}"
          fi
        }

        install_language "gcc" "10.2.0"
        install_language "python" "3.12.0"
        install_language "java" "15.0.2"

volumes:
  postgres_data:
  piston_packages:
